#Server configurations
server.port=5055

#DB configurations
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/green_shadow_springboot?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=Kavindu44444

#JPA with Hibernate configurations
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Specify the log level (INFO, DEBUG, etc.)
logging.level.root=INFO

# Set the logging pattern for the file
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss}%msg%n

#JWTKey
token.key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkthdmluZHUgU2VuZXNoIiwiaWF0IjoxNTE2MjM5MDIyfQ.u0kqdctRXu2ZnJSZwbMG7dTNbQBLXAinAnULxtAeqwo